### ISSUE TITLE
Support for Asynchronous Operations

### ISSUE THREAD

**Issue by WardLT** [DLHub-Argonne/dlhub_service#9]
Add ability to perform asynchronous requests. Will require:

- [x] Updating `run` API calls to return Task ID
- [x] Some kind of database/cache for holding result objects

**Comment by blaiszik** [comment]
Do we want 1) everything to be async; 2) an added arg to run(async=True) to set async; or 3) run_async() (name could be different) as a separate function? I can see arguments for each. 

1) + Behavior of run() is always async and always as expected. - You need two requests to get even the simplest results
2) +Everything always uses run() - Behavior of run is very different depending on one arg. 
3) + Each function run and run_async always acts exactly as expected -Added complexity with another function and perhaps duplicate code in the two functions.

**Comment by WardLT** [comment]
Good question and good points, @blaiszik !

I'm in favor having two separate functions for "async" and "synchronous" (option 3). Seems like the easiest option for the user perspective.

**Comment by blaiszik** [comment]
Seems like a good idea to me as long as we can keep code duplication to a minimum.
